version: "3"
services:
  oracle-local:
    container_name: oracle-local
    image: store/oracle/database-enterprise:12.2.0.1
    ports:
      - "32769:1521"
    volumes:
      - ./SQL:/var/SQL
      - ./shell_scripts/container:/var/shell_scripts
