create user c##local identified by localpass;

grant dba to c##local;

grant create session to c##local with admin option;

GRANT CREATE TABLE TO c##local;
GRANT CREATE SEQUENCE TO c##local;
GRANT CREATE PROCEDURE TO c##local;
GRANT CREATE TRIGGER TO c##local;
GRANT CREATE USER TO c##local;
GRANT ALTER USER TO c##local;
GRANT DROP USER TO c##local;
GRANT CREATE TABLESPACE TO c##local;
GRANT DROP TABLESPACE TO c##local;
GRANT CREATE SESSION TO c##local WITH ADMIN OPTION;
GRANT CREATE TABLE TO c##local WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO c##local WITH ADMIN OPTION;
GRANT CREATE PROCEDURE TO c##local WITH ADMIN OPTION;
GRANT CREATE TRIGGER TO c##local WITH ADMIN OPTION;
GRANT CREATE VIEW TO c##local WITH ADMIN OPTION;
GRANT EXECUTE ON SYS.DBMS_LOB TO c##local;
GRANT EXECUTE ON SYS.DBMS_RANDOM TO c##local;