CREATE TABLE THING_TYPE
(
    THING_TYPE_CODE VARCHAR2(3) NOT NULL PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL CONSTRAINT THING_TYPE_UK UNIQUE
);

CREATE TABLE PERSON
(
    PERSON_ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL CONSTRAINT PERSON_UK UNIQUE
);


CREATE TABLE THING
(
    THING_ID INTEGER NOT NULL PRIMARY KEY,
    PERSON_ID INTEGER REFERENCES PERSON(PERSON_ID),
    DATE_CREATED DATE NOT NULL,
    THING_TYPE_CODE VARCHAR2(3) REFERENCES THING_TYPE(THING_TYPE_CODE)
);

CREATE INDEX THING_PERSON_IDX ON THING(PERSON_ID);

CREATE TABLE CAR
(
    CAR_ID INTEGER NOT NULL PRIMARY KEY,
    THING_ID INTEGER REFERENCES THING(THING_ID),
    DETAIL VARCHAR2(4000) NOT NULL
);

CREATE INDEX CAR_THING_IDX ON CAR(THING_ID);

CREATE TABLE HOUSE
(
    HOUSE_ID INTEGER NOT NULL PRIMARY KEY,
    THING_ID INTEGER REFERENCES THING(THING_ID),
    DETAIL VARCHAR2(4000) NOT NULL
);

CREATE INDEX HOUSE_THING_IDX ON HOUSE(THING_ID);
